runtime: python39
instance_class: F1 # default F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0
  min_idle_instances: 0
  min_pending_latency: 3000ms
  max_pending_latency: 9000ms
  max_concurrent_requests: 80

handlers:
- url: /sendJamInfo
  script: auto
  #login: admin  # only by admin (cron, etc)

- url: /checkAlive
  script: auto
  #login: admin  # only by admin (cron, etc)

- url: /checkAliveOfWebOnGCE
  script: auto
  #login: admin  # only by admin (cron, etc)

- url: /sendStock
  script: auto
  #login: admin  # only by admin (cron, etc)


# url not defined here is handled in default manner (script=main.py, etc)


